package com.qiujintao.mapper;

import com.qiujintao.model.Paragraph;
import com.qiujintao.model.ParagraphExample;
import com.qiujintao.model.ParagraphWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParagraphMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paragraph
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    long countByExample(ParagraphExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paragraph
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    int deleteByExample(ParagraphExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paragraph
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paragraph
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    int insert(ParagraphWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paragraph
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    int insertSelective(ParagraphWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paragraph
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    List<ParagraphWithBLOBs> selectByExampleWithBLOBs(ParagraphExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paragraph
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    List<Paragraph> selectByExample(ParagraphExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paragraph
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    ParagraphWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paragraph
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") ParagraphWithBLOBs record, @Param("example") ParagraphExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paragraph
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ParagraphWithBLOBs record, @Param("example") ParagraphExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paragraph
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    int updateByExample(@Param("record") Paragraph record, @Param("example") ParagraphExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paragraph
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    int updateByPrimaryKeySelective(ParagraphWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paragraph
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ParagraphWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paragraph
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    int updateByPrimaryKey(Paragraph record);
}