package com.qiujintao.model;

import java.util.List;

import javax.validation.Valid;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Date;

public class Article {



	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.user_id
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	private Integer user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.creation_date
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	private Date creation_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.last_update
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	private Date last_update;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.image
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.creation_date
	 * @return  the value of article.creation_date
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	public Date getCreation_date() {
		return creation_date;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.creation_date
	 * @param creation_date  the value for article.creation_date
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	public void setCreation_date(Date creation_date) {
		this.creation_date = creation_date;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.last_update
	 * @return  the value of article.last_update
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	public Date getLast_update() {
		return last_update;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.last_update
	 * @param last_update  the value for article.last_update
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	public void setLast_update(Date last_update) {
		this.last_update = last_update;
	}

	private Integer id;
	@NotEmpty
	@Size(max=255)
	private String title;
	@Size(max=16777215)
	private byte[] image;
	@Size(max=500)
	private String excerpt;
	@NotNull
	@Valid
	private List<ParagraphWithBLOBs> paragraphs;
	public Article() {}
	public Article(String title, List<ParagraphWithBLOBs> paragraphs) {
		this.title = title;
		this.paragraphs= paragraphs;
	}
	public List<ParagraphWithBLOBs> getParagraphs() {
		return paragraphs;
	}
	public Integer getUser_id() {
		return user_id;
	}
	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}
	public void setParagraphs(List<ParagraphWithBLOBs> paragraphs) {
		this.paragraphs = paragraphs;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getExcerpt() {
		return excerpt;
	}
	public void setExcerpt(String excerpt) {
		this.excerpt = excerpt;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public byte[] getImage() {
		return image;
	}
	public void setImage(byte[] image) {
		this.image = image;
	}
	@Override
	public String toString() {
		return "[id: "+id+",title: "+title+",image: "+(image==null?null:new String(image))+", paragraphs: "+(paragraphs==null?null:paragraphs.toString())+"]";
	}
	
}
