package com.qiujintao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArticleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table article
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table article
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table article
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	public ArticleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table article
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andExcerptIsNull() {
			addCriterion("excerpt is null");
			return (Criteria) this;
		}

		public Criteria andExcerptIsNotNull() {
			addCriterion("excerpt is not null");
			return (Criteria) this;
		}

		public Criteria andExcerptEqualTo(String value) {
			addCriterion("excerpt =", value, "excerpt");
			return (Criteria) this;
		}

		public Criteria andExcerptNotEqualTo(String value) {
			addCriterion("excerpt <>", value, "excerpt");
			return (Criteria) this;
		}

		public Criteria andExcerptGreaterThan(String value) {
			addCriterion("excerpt >", value, "excerpt");
			return (Criteria) this;
		}

		public Criteria andExcerptGreaterThanOrEqualTo(String value) {
			addCriterion("excerpt >=", value, "excerpt");
			return (Criteria) this;
		}

		public Criteria andExcerptLessThan(String value) {
			addCriterion("excerpt <", value, "excerpt");
			return (Criteria) this;
		}

		public Criteria andExcerptLessThanOrEqualTo(String value) {
			addCriterion("excerpt <=", value, "excerpt");
			return (Criteria) this;
		}

		public Criteria andExcerptLike(String value) {
			addCriterion("excerpt like", value, "excerpt");
			return (Criteria) this;
		}

		public Criteria andExcerptNotLike(String value) {
			addCriterion("excerpt not like", value, "excerpt");
			return (Criteria) this;
		}

		public Criteria andExcerptIn(List<String> values) {
			addCriterion("excerpt in", values, "excerpt");
			return (Criteria) this;
		}

		public Criteria andExcerptNotIn(List<String> values) {
			addCriterion("excerpt not in", values, "excerpt");
			return (Criteria) this;
		}

		public Criteria andExcerptBetween(String value1, String value2) {
			addCriterion("excerpt between", value1, value2, "excerpt");
			return (Criteria) this;
		}

		public Criteria andExcerptNotBetween(String value1, String value2) {
			addCriterion("excerpt not between", value1, value2, "excerpt");
			return (Criteria) this;
		}

		public Criteria andUser_idIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUser_idIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUser_idEqualTo(Integer value) {
			addCriterion("user_id =", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idGreaterThan(Integer value) {
			addCriterion("user_id >", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idLessThan(Integer value) {
			addCriterion("user_id <", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idIn(List<Integer> values) {
			addCriterion("user_id in", values, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "user_id");
			return (Criteria) this;
		}

		public Criteria andCreation_dateIsNull() {
			addCriterion("creation_date is null");
			return (Criteria) this;
		}

		public Criteria andCreation_dateIsNotNull() {
			addCriterion("creation_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreation_dateEqualTo(Date value) {
			addCriterion("creation_date =", value, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateNotEqualTo(Date value) {
			addCriterion("creation_date <>", value, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateGreaterThan(Date value) {
			addCriterion("creation_date >", value, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateGreaterThanOrEqualTo(Date value) {
			addCriterion("creation_date >=", value, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateLessThan(Date value) {
			addCriterion("creation_date <", value, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateLessThanOrEqualTo(Date value) {
			addCriterion("creation_date <=", value, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateIn(List<Date> values) {
			addCriterion("creation_date in", values, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateNotIn(List<Date> values) {
			addCriterion("creation_date not in", values, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateBetween(Date value1, Date value2) {
			addCriterion("creation_date between", value1, value2, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateNotBetween(Date value1, Date value2) {
			addCriterion("creation_date not between", value1, value2, "creation_date");
			return (Criteria) this;
		}

		public Criteria andLast_updateIsNull() {
			addCriterion("last_update is null");
			return (Criteria) this;
		}

		public Criteria andLast_updateIsNotNull() {
			addCriterion("last_update is not null");
			return (Criteria) this;
		}

		public Criteria andLast_updateEqualTo(Date value) {
			addCriterion("last_update =", value, "last_update");
			return (Criteria) this;
		}

		public Criteria andLast_updateNotEqualTo(Date value) {
			addCriterion("last_update <>", value, "last_update");
			return (Criteria) this;
		}

		public Criteria andLast_updateGreaterThan(Date value) {
			addCriterion("last_update >", value, "last_update");
			return (Criteria) this;
		}

		public Criteria andLast_updateGreaterThanOrEqualTo(Date value) {
			addCriterion("last_update >=", value, "last_update");
			return (Criteria) this;
		}

		public Criteria andLast_updateLessThan(Date value) {
			addCriterion("last_update <", value, "last_update");
			return (Criteria) this;
		}

		public Criteria andLast_updateLessThanOrEqualTo(Date value) {
			addCriterion("last_update <=", value, "last_update");
			return (Criteria) this;
		}

		public Criteria andLast_updateIn(List<Date> values) {
			addCriterion("last_update in", values, "last_update");
			return (Criteria) this;
		}

		public Criteria andLast_updateNotIn(List<Date> values) {
			addCriterion("last_update not in", values, "last_update");
			return (Criteria) this;
		}

		public Criteria andLast_updateBetween(Date value1, Date value2) {
			addCriterion("last_update between", value1, value2, "last_update");
			return (Criteria) this;
		}

		public Criteria andLast_updateNotBetween(Date value1, Date value2) {
			addCriterion("last_update not between", value1, value2, "last_update");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table article
	 * @mbg.generated  Wed Aug 22 21:17:55 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 21 20:40:11 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}