package com.qiujintao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CommentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comment
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comment
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comment
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public CommentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comment
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andContextIsNull() {
			addCriterion("context is null");
			return (Criteria) this;
		}

		public Criteria andContextIsNotNull() {
			addCriterion("context is not null");
			return (Criteria) this;
		}

		public Criteria andContextEqualTo(String value) {
			addCriterion("context =", value, "context");
			return (Criteria) this;
		}

		public Criteria andContextNotEqualTo(String value) {
			addCriterion("context <>", value, "context");
			return (Criteria) this;
		}

		public Criteria andContextGreaterThan(String value) {
			addCriterion("context >", value, "context");
			return (Criteria) this;
		}

		public Criteria andContextGreaterThanOrEqualTo(String value) {
			addCriterion("context >=", value, "context");
			return (Criteria) this;
		}

		public Criteria andContextLessThan(String value) {
			addCriterion("context <", value, "context");
			return (Criteria) this;
		}

		public Criteria andContextLessThanOrEqualTo(String value) {
			addCriterion("context <=", value, "context");
			return (Criteria) this;
		}

		public Criteria andContextLike(String value) {
			addCriterion("context like", value, "context");
			return (Criteria) this;
		}

		public Criteria andContextNotLike(String value) {
			addCriterion("context not like", value, "context");
			return (Criteria) this;
		}

		public Criteria andContextIn(List<String> values) {
			addCriterion("context in", values, "context");
			return (Criteria) this;
		}

		public Criteria andContextNotIn(List<String> values) {
			addCriterion("context not in", values, "context");
			return (Criteria) this;
		}

		public Criteria andContextBetween(String value1, String value2) {
			addCriterion("context between", value1, value2, "context");
			return (Criteria) this;
		}

		public Criteria andContextNotBetween(String value1, String value2) {
			addCriterion("context not between", value1, value2, "context");
			return (Criteria) this;
		}

		public Criteria andUser_idIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUser_idIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUser_idEqualTo(Integer value) {
			addCriterion("user_id =", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idGreaterThan(Integer value) {
			addCriterion("user_id >", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idLessThan(Integer value) {
			addCriterion("user_id <", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idIn(List<Integer> values) {
			addCriterion("user_id in", values, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "user_id");
			return (Criteria) this;
		}

		public Criteria andCreation_dateIsNull() {
			addCriterion("creation_date is null");
			return (Criteria) this;
		}

		public Criteria andCreation_dateIsNotNull() {
			addCriterion("creation_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreation_dateEqualTo(Date value) {
			addCriterion("creation_date =", value, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateNotEqualTo(Date value) {
			addCriterion("creation_date <>", value, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateGreaterThan(Date value) {
			addCriterion("creation_date >", value, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateGreaterThanOrEqualTo(Date value) {
			addCriterion("creation_date >=", value, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateLessThan(Date value) {
			addCriterion("creation_date <", value, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateLessThanOrEqualTo(Date value) {
			addCriterion("creation_date <=", value, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateIn(List<Date> values) {
			addCriterion("creation_date in", values, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateNotIn(List<Date> values) {
			addCriterion("creation_date not in", values, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateBetween(Date value1, Date value2) {
			addCriterion("creation_date between", value1, value2, "creation_date");
			return (Criteria) this;
		}

		public Criteria andCreation_dateNotBetween(Date value1, Date value2) {
			addCriterion("creation_date not between", value1, value2, "creation_date");
			return (Criteria) this;
		}

		public Criteria andReply_to_comment_idIsNull() {
			addCriterion("reply_to_comment_id is null");
			return (Criteria) this;
		}

		public Criteria andReply_to_comment_idIsNotNull() {
			addCriterion("reply_to_comment_id is not null");
			return (Criteria) this;
		}

		public Criteria andReply_to_comment_idEqualTo(Integer value) {
			addCriterion("reply_to_comment_id =", value, "reply_to_comment_id");
			return (Criteria) this;
		}

		public Criteria andReply_to_comment_idNotEqualTo(Integer value) {
			addCriterion("reply_to_comment_id <>", value, "reply_to_comment_id");
			return (Criteria) this;
		}

		public Criteria andReply_to_comment_idGreaterThan(Integer value) {
			addCriterion("reply_to_comment_id >", value, "reply_to_comment_id");
			return (Criteria) this;
		}

		public Criteria andReply_to_comment_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("reply_to_comment_id >=", value, "reply_to_comment_id");
			return (Criteria) this;
		}

		public Criteria andReply_to_comment_idLessThan(Integer value) {
			addCriterion("reply_to_comment_id <", value, "reply_to_comment_id");
			return (Criteria) this;
		}

		public Criteria andReply_to_comment_idLessThanOrEqualTo(Integer value) {
			addCriterion("reply_to_comment_id <=", value, "reply_to_comment_id");
			return (Criteria) this;
		}

		public Criteria andReply_to_comment_idIn(List<Integer> values) {
			addCriterion("reply_to_comment_id in", values, "reply_to_comment_id");
			return (Criteria) this;
		}

		public Criteria andReply_to_comment_idNotIn(List<Integer> values) {
			addCriterion("reply_to_comment_id not in", values, "reply_to_comment_id");
			return (Criteria) this;
		}

		public Criteria andReply_to_comment_idBetween(Integer value1, Integer value2) {
			addCriterion("reply_to_comment_id between", value1, value2, "reply_to_comment_id");
			return (Criteria) this;
		}

		public Criteria andReply_to_comment_idNotBetween(Integer value1, Integer value2) {
			addCriterion("reply_to_comment_id not between", value1, value2, "reply_to_comment_id");
			return (Criteria) this;
		}

		public Criteria andDeletedIsNull() {
			addCriterion("deleted is null");
			return (Criteria) this;
		}

		public Criteria andDeletedIsNotNull() {
			addCriterion("deleted is not null");
			return (Criteria) this;
		}

		public Criteria andDeletedEqualTo(Boolean value) {
			addCriterion("deleted =", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotEqualTo(Boolean value) {
			addCriterion("deleted <>", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedGreaterThan(Boolean value) {
			addCriterion("deleted >", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("deleted >=", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedLessThan(Boolean value) {
			addCriterion("deleted <", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
			addCriterion("deleted <=", value, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedIn(List<Boolean> values) {
			addCriterion("deleted in", values, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotIn(List<Boolean> values) {
			addCriterion("deleted not in", values, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
			addCriterion("deleted between", value1, value2, "deleted");
			return (Criteria) this;
		}

		public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("deleted not between", value1, value2, "deleted");
			return (Criteria) this;
		}

		public Criteria andReply_countIsNull() {
			addCriterion("reply_count is null");
			return (Criteria) this;
		}

		public Criteria andReply_countIsNotNull() {
			addCriterion("reply_count is not null");
			return (Criteria) this;
		}

		public Criteria andReply_countEqualTo(Integer value) {
			addCriterion("reply_count =", value, "reply_count");
			return (Criteria) this;
		}

		public Criteria andReply_countNotEqualTo(Integer value) {
			addCriterion("reply_count <>", value, "reply_count");
			return (Criteria) this;
		}

		public Criteria andReply_countGreaterThan(Integer value) {
			addCriterion("reply_count >", value, "reply_count");
			return (Criteria) this;
		}

		public Criteria andReply_countGreaterThanOrEqualTo(Integer value) {
			addCriterion("reply_count >=", value, "reply_count");
			return (Criteria) this;
		}

		public Criteria andReply_countLessThan(Integer value) {
			addCriterion("reply_count <", value, "reply_count");
			return (Criteria) this;
		}

		public Criteria andReply_countLessThanOrEqualTo(Integer value) {
			addCriterion("reply_count <=", value, "reply_count");
			return (Criteria) this;
		}

		public Criteria andReply_countIn(List<Integer> values) {
			addCriterion("reply_count in", values, "reply_count");
			return (Criteria) this;
		}

		public Criteria andReply_countNotIn(List<Integer> values) {
			addCriterion("reply_count not in", values, "reply_count");
			return (Criteria) this;
		}

		public Criteria andReply_countBetween(Integer value1, Integer value2) {
			addCriterion("reply_count between", value1, value2, "reply_count");
			return (Criteria) this;
		}

		public Criteria andReply_countNotBetween(Integer value1, Integer value2) {
			addCriterion("reply_count not between", value1, value2, "reply_count");
			return (Criteria) this;
		}

		public Criteria andArticle_idIsNull() {
			addCriterion("article_id is null");
			return (Criteria) this;
		}

		public Criteria andArticle_idIsNotNull() {
			addCriterion("article_id is not null");
			return (Criteria) this;
		}

		public Criteria andArticle_idEqualTo(Integer value) {
			addCriterion("article_id =", value, "article_id");
			return (Criteria) this;
		}

		public Criteria andArticle_idNotEqualTo(Integer value) {
			addCriterion("article_id <>", value, "article_id");
			return (Criteria) this;
		}

		public Criteria andArticle_idGreaterThan(Integer value) {
			addCriterion("article_id >", value, "article_id");
			return (Criteria) this;
		}

		public Criteria andArticle_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("article_id >=", value, "article_id");
			return (Criteria) this;
		}

		public Criteria andArticle_idLessThan(Integer value) {
			addCriterion("article_id <", value, "article_id");
			return (Criteria) this;
		}

		public Criteria andArticle_idLessThanOrEqualTo(Integer value) {
			addCriterion("article_id <=", value, "article_id");
			return (Criteria) this;
		}

		public Criteria andArticle_idIn(List<Integer> values) {
			addCriterion("article_id in", values, "article_id");
			return (Criteria) this;
		}

		public Criteria andArticle_idNotIn(List<Integer> values) {
			addCriterion("article_id not in", values, "article_id");
			return (Criteria) this;
		}

		public Criteria andArticle_idBetween(Integer value1, Integer value2) {
			addCriterion("article_id between", value1, value2, "article_id");
			return (Criteria) this;
		}

		public Criteria andArticle_idNotBetween(Integer value1, Integer value2) {
			addCriterion("article_id not between", value1, value2, "article_id");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table comment
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 02 10:09:28 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}