package com.qiujintao.model;

import java.util.Date;

public class Comment {
	
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	private User user;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.id
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.context
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	private String context;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.user_id
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	private Integer user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.creation_date
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	private Date creation_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.reply_to_comment_id
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	private Integer reply_to_comment_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.deleted
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	private Boolean deleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.reply_count
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	private Integer reply_count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.article_id
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	private Integer article_id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.id
	 * @return  the value of comment.id
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.id
	 * @param id  the value for comment.id
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.context
	 * @return  the value of comment.context
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public String getContext() {
		return context;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.context
	 * @param context  the value for comment.context
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public void setContext(String context) {
		this.context = context;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.user_id
	 * @return  the value of comment.user_id
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public Integer getUser_id() {
		return user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.user_id
	 * @param user_id  the value for comment.user_id
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.creation_date
	 * @return  the value of comment.creation_date
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public Date getCreation_date() {
		return creation_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.creation_date
	 * @param creation_date  the value for comment.creation_date
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public void setCreation_date(Date creation_date) {
		this.creation_date = creation_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.reply_to_comment_id
	 * @return  the value of comment.reply_to_comment_id
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public Integer getReply_to_comment_id() {
		return reply_to_comment_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.reply_to_comment_id
	 * @param reply_to_comment_id  the value for comment.reply_to_comment_id
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public void setReply_to_comment_id(Integer reply_to_comment_id) {
		this.reply_to_comment_id = reply_to_comment_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.deleted
	 * @return  the value of comment.deleted
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public Boolean getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.deleted
	 * @param deleted  the value for comment.deleted
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.reply_count
	 * @return  the value of comment.reply_count
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public Integer getReply_count() {
		return reply_count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.reply_count
	 * @param reply_count  the value for comment.reply_count
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public void setReply_count(Integer reply_count) {
		this.reply_count = reply_count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.article_id
	 * @return  the value of comment.article_id
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public Integer getArticle_id() {
		return article_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.article_id
	 * @param article_id  the value for comment.article_id
	 * @mbg.generated  Tue Oct 02 10:35:44 CST 2018
	 */
	public void setArticle_id(Integer article_id) {
		this.article_id = article_id;
	}
}