package com.qiujintao.model;

import java.util.regex.Pattern;

import javax.validation.constraints.Size;

public class ParagraphWithBLOBs extends Paragraph {
	static private Pattern printableCharacterPattern = Pattern.compile("^(?!^\\s+$)((\\P{Cc})+).{0,}$");
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paragraph.text
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
	@Size(max = 65000)
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paragraph.image
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    @Size(max=16777215)
    private byte[] image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paragraph.text
     *
     * @return the value of paragraph.text
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paragraph.text
     *
     * @param text the value for paragraph.text
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
	public void setText(String text) {
		if(image!=null&&text!=null) {
			throw new IllegalStateException("text cannot be populated to null in a Paragraph object!");
		}
		if(!(printableCharacterPattern.matcher(text).matches())) {
			throw new IllegalStateException("text cannot be non printable in a Paragraph object!");
		}
		
		this.text = text;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paragraph.image
     *
     * @return the value of paragraph.image
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */
    public byte[] getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paragraph.image
     *
     * @param image the value for paragraph.image
     *
     * @mbg.generated Tue Aug 21 20:40:11 CST 2018
     */

	public void setImage(byte[] image) {
		if(text!=null&&image!=null) {
			throw new IllegalStateException("image and text cannot be populated at the same time in a Paragraph object!");
		}
		this.image = image;
	}
	@Override
	public String toString() {
		if(image == null) {
			return "p: "+text;
		}else {
			return "img: "+new String(image)+", imageCaption: "+(this.getImageCaption()==null?"not caption":this.getImageCaption());
		}
		
	}
}