package com.qiujintao.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.lastName
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	private String lastname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.firstName
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	private String firstname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.nickName
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.passwordHash
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	private String passwordhash;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.active
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	private Boolean active;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.role
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	private String role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.image
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	private byte[] image;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.lastName
	 * @return  the value of user.lastName
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public String getLastname() {
		return lastname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.lastName
	 * @param lastname  the value for user.lastName
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.firstName
	 * @return  the value of user.firstName
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public String getFirstname() {
		return firstname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.firstName
	 * @param firstname  the value for user.firstName
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.nickName
	 * @return  the value of user.nickName
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.nickName
	 * @param nickname  the value for user.nickName
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.passwordHash
	 * @return  the value of user.passwordHash
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public String getPasswordhash() {
		return passwordhash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.passwordHash
	 * @param passwordhash  the value for user.passwordHash
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public void setPasswordhash(String passwordhash) {
		this.passwordhash = passwordhash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.active
	 * @return  the value of user.active
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public Boolean getActive() {
		return active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.active
	 * @param active  the value for user.active
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public void setActive(Boolean active) {
		this.active = active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.role
	 * @return  the value of user.role
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.role
	 * @param role  the value for user.role
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public void setRole(String role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.image
	 * @return  the value of user.image
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public byte[] getImage() {
		return image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.image
	 * @param image  the value for user.image
	 * @mbg.generated  Tue Jul 24 21:07:40 CST 2018
	 */
	public void setImage(byte[] image) {
		this.image = image;
	}
}